# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'glimmer-dsl-libui', '~> 0.2.13'
gem 'befunge98', '0.0.2'

group :development do
  gem 'rspec', '~> 3.5.0'
  gem 'juwelier', '2.4.9'
  gem 'warbler', '2.0.5'
  gem 'simplecov', '>= 0'
  gem 'puts_debuggerer', '>= 0'
end
